### ISSUE TITLE
[api] Add S3 settings to the prod config

### ISSUE THREAD

**Issue by aramboi** [code4romania/seismic-risc#108]
This is mainly used for storing the blog inline images, but could be used for all other image/file uploads.

**Comment by lorenabalan** [comment]
I can pick this up. 🙃

**Comment by calindragomir** [comment]
hi @lorenabalan , please do, this is something that I said I would pick-up but I did not find the time to do it.
Unless @tudoramariei has anything against it, I don't have any progress on it.

**Comment by tudoramariei** [comment]
Hi, @lorenabalan! Sorry for the late response and sorry for leaving this open
The work was done, but I forgot to close the issue 😓 

This is how we implemented it:
https://github.com/code4romania/seismic-risc/blob/develop/api/seismic_site/settings/base.py#LL160C0-L181C0
If you have any feedback, it's very welcome since I based it on the implementation of other Django projects.
