### ISSUE TITLE
Changing the maps provider to open street maps

### ISSUE THREAD

**Issue by tudorgergely** [code4romania/seismic-risc#225]
I've noticed the project uses Here! Maps as a maps provider. Is there an objective reason for this? It seems to be very badly supported in ReactJS. 

I think we can still make the switch to something better supported and maybe open-source - like OpenStreetMap, which can be used with leaflet https://react-leaflet.js.org/ or with pigeon https://pigeon-maps.js.org/ which both have their own ReactJS component for most tasks/events already implemented.

**Comment by tudoramariei** [comment]
Hey, @tudorgergely!
We're using `Here! Maps` because of the simpler implementation. In this case, we only need to use their API and we should be set while in the case of `OpenStreetMap` we would have to deploy our map server, which would end up in a big overhead cost. Besides deploying it we'll also have to maintain it.
Right now we don't have the bandwidth to manage this, so we won't be changing the map provider very soon.

**Comment by tudorgergely** [comment]
That's totally reasonable and I also thought that is the main reason. There is, of course, a free OSM tile server but I'm not sure we are allowed to use it (although this isn't a commercial use so we should be fine). 

Why don't we use react-leaflet though? It's way easier than recreating all the functionality ourselves for map interactions/markers and it works with Here! Maps as well.

**Comment by tudorgergely** [comment]
If this is something desirable I can work on it btw

**Comment by tudorgergely** [comment]
I'll close this for now as it is not a priority.
