### ISSUE TITLE
Enable Discussions Tab for this repository from Repo Settings

### ISSUE THREAD

**Issue by mateesville93** [code4romania/seismic-risc#517]
I don't like to open an Issue when I have some general questions or ideas. Like this one.

**Comment by catileptic** [comment]
We absolutely welcome questions and ideas raised as issues! Wanna tell us more about what you were considering?

If you prefer to send us documents, you can reach us at `contact@code4.ro`. This address is also present in all the READMEs attached to our projects. 

The Discussion tab is a feature we have not enabled yet for our repos, due to the fact that managing another channel where we have dev discussions is going to be very burdensome for an already-too-small team of volunteers which we have in Code for Romania.

**Comment by mateesville93** [comment]
I see, thank you!
