### ISSUE TITLE
[api] Add an api documentation generation solution

### ISSUE THREAD

**Issue by aramboi** [code4romania/seismic-risc#98]
We should have a way to document the api and a way to test or interact with it dynamically.

Lucky for us, most of the work is done in the form of [drf-yasg - Yet another Swagger generator](https://drf-yasg.readthedocs.io/en/stable/index.html), so we could try to use this.

We are also opened to suggestions from the community.

**Comment by lzomedia** [comment]
why not swagger 
https://django-rest-swagger.readthedocs.io/en/latest/

**Comment by aramboi** [comment]
Last commit to [marcgibbons/django-rest-swagger](https://github.com/marcgibbons/django-rest-swagger/) is more than a year ago. Also, the readme states the project is no longer actively maintained and recommends [axnsan12/drf-yasg](https://github.com/axnsan12/drf-yasg ) (same project as in the this ticket description).

**Comment by GabrielMajeri** [comment]
I've started reading the `drf-yasg` documentation, and they recomended using https://github.com/tfranzel/drf-spectacular if we want OpenAPI 3.0 support. Is it a good solution?

**Comment by catileptic** [comment]
From what I can see, the difference is that [drf-yasg](https://github.com/axnsan12/drf-yasg) supports up to OpenApi 2 and [drf-spectacular](https://github.com/tfranzel/drf-spectacular) supports OpenApi 3. Since I don't think we're using anything OpenApi 3 specific, I think we're fine with either. [drf-spectacular](https://github.com/tfranzel/drf-spectacular) seems to have more recent commits as of the time I am writing this comment, so based on a completely arbitrary metric, I'd say let's go with this one. 

@GabrielMajeri would you like to have a go at this Issue?

**Comment by tudoramariei** [comment]
We already have @juliageek working on the issue and PR #652 is ready for review
